apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
spec:
  type: NodePort
  clusterIP: 10.233.10.10   	# 생략 가능(생략하면 IP 자동할당)
  selector:
    app: webui
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30200   			# 생략 가능(생략하면 Port 자동할당)
